### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space Error

### ISSUE THREAD

**Issue by xnl-h4ck3r** [marduc812/BurpSuiteHistoryExplorer#3]
Hi
I have a project that is 8.75GB. I can search fine in the Burp Suite Search with a regex, but when I tried with a simple regex on the History Explorer, it took a long time to respond and gave no results because it logged the error below in the Extension Error pane:

```
java.lang.OutOfMemoryError: Java heap space
	at net.portswigger.Zo6.ZU(Unknown Source)
	at net.portswigger.Zo6.Zu(Unknown Source)
	at burp.Zyvf.ZX1(Unknown Source)
	at burp.Zyzz.toString(Unknown Source)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x000000080011e800.invokeVirtual(LambdaForm$DMH)
	at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:153)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at burp.Znqa.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy89.toString(Unknown Source)
	at com.marduc812.HistoryExplorer.lambda$new$0(HistoryExplorer.java:97)
	at com.marduc812.HistoryExplorer$$Lambda/0x0000000801a53288.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at com.marduc812.HistoryExplorer.<init>(HistoryExplorer.java:62)
	at com.marduc812.HistoryExplorerGui$1.actionPerformed(HistoryExplorerGui.java:77)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	```
	I'm not too sure what can be done about that, but I thought I'd raise it. Thanks

**Comment by marduc812** [comment]
Fixed at https://github.com/marduc812/BurpSuiteHistoryExplorer/commit/aa863ed90af1ac2ac04ecb6dde488de378112053
thanks for bring it up @xnl-h4ck3r
